# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj|
# is minimised; what is the value of D?

def isPentagonal(num):
    test= (1+(1+24*num)**(1/2))/6
    if test%1==0:
        return True
    return False

pentagon=[]
for i in range(1,10000):
    res=i*(3*i-1)/2
    pentagon.append(int(res))

pentagonPlus=[]
for i in pentagon:
    for j in pentagon[pentagon.index(i):]:
        plus=i+j
        minus=j-i
        if isPentagonal(plus)==True and isPentagonal(minus)==True:
            pentagonPlus.append((i,j))

print(pentagonPlus)